### ISSUE TITLE
Got stack trace on install

### ISSUE THREAD

**Issue by CMurtagh-LGTM** [jakobkmar/pacmc#26]
Got a timeout installing `Presence Footsteps 1.4.0`
```
❯ pacmc install Presence
Searching for installable mods matching 'Presence'

1) modrinth/Presence Footsteps [rcTfTZr3] by Sollace
  ..An Overly complicated Sound Mod...
2) modrinth/Fabripresence [vIWqtF8n] by arencos not available for 1.18.1
  Configurable Discord Rich Presence for Fabric
3) modrinth/MoreCommands [duhqx1QT] by planetteamspeakk not available for 1.18.1
  Adds 79 commands, many tweaks, Discord Rich Presence support, the ability to sit on stairs, really cool RAINBOWS and more!
4) curseforge/Rich Presence Mod [509434] by hotlava02 not available for 1.18.1
  Highly customizable fabric mod to show rich presence in Discord with Minecraft info.
5) curseforge/Presence Footsteps [334259] by S0llace
  An overly complicated sound mod

Which mod do you want to install? (1, 2, 3, 4, 5) 1

Installing the mod at /home/cameron/.minecraft/mods

Downloading modrinth/Presence Footsteps 1.4.0
kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 15000 ms
	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:191)
	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:161)
	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:507)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:69)
	at java.base/java.lang.Thread.run(Thread.java:833)
An error occured, Please open an issue with the above stack trace at https://github.com/jakobkmar/pacmc/issues/new
```
```
❯ pacmc debug
pacmc version 0.4.2

dataLocalDir: /home/cameron/.local/share/pacmc
databaseDir: /home/cameron/.local/share/pacmc/db1
databaseDir (canonical): /home/cameron/.local/share/pacmc/db1

Your OS: LINUX
Java version: 17.0.1+12
```
```
❯ pacmc list
The archive '.minecraft' at /home/cameron/.minecraft/mods contains the following mods:

 → Illuminations 🔥 [curseforge/292908]
    A client mod that adds fireflies and various glow-in-the-dark ambient particles to your world.
 → Physics Mod [curseforge/442735]
    Adds physics to Mobs and Blocks!
 → Farsight[Forge/Fabric] [curseforge/495693]
    See far chunks on clientside, even if the server has low view distance
 → Effective 💦 [curseforge/556381]
    A client-side mod adding ambient and environmental interaction effects to enhance immersion.
 → Sodium [modrinth/AANobbMI]
    Modern rendering engine and client-side optimization mod for Minecraft
 → Iris Shaders [modrinth/YL57xq9U]
    A modern shaders mod for Minecraft intended to be compatible with existing OptiFine shader packs
 → Presence Footsteps [modrinth/rcTfTZr3]
    ..An Overly complicated Sound Mod...
 → LambDynamicLights [modrinth/yBW8D80W]
    A dynamic lights mod for Fabric.

 → Fabric API [curseforge/306612] (dependency)
    Core API library for the Fabric toolchain
```

**Comment by CMurtagh-LGTM** [comment]
It looks like the curseforge version works :thinking:

**Comment by jakobkmar** [comment]
Mh, it works for me:
![image](https://user-images.githubusercontent.com/52456572/149960659-9f20b4c2-4793-4593-96c5-9b9206ddedf4.png)

As it is a timeout, there probably was either a problem with your internet connection or with the Modrinth servers.

Could you try to install Presence Footsteps again?

If it it still does not work for you, I could increase the timeout threshold.

**Comment by CMurtagh-LGTM** [comment]
Yeah, trying it now works as expected. Your probably right about it being my internet, it can be inconsistent.

I think that perhaps for a timeout error it might be safe to assume that its the user's connection and tell them to try again a bit later :thinking:.

**Comment by jakobkmar** [comment]
Yes it would be better to catch that exception and display a concise error message there.

**Comment by CMurtagh-LGTM** [comment]
Found another one,
```
❯ pacmc install 360438
Searching for installable mods matching '360438'
Got a Gateway Time-out answer (code 504) for the following request: https://addons-ecs.forgesvc.net/api/v2/addon/360438/files
Please open an issue with the above error message at https://github.com/jakobkmar/pacmc/issues/new
Could not find anything for the given mod '360438'
❯ pacmc install 360438
Searching for installable mods matching '360438'
Installing the mod at /home/cameron/.minecraft/mods

Downloading curseforge/Lithium (Fabric) 1.18.1-0.7.7
  [──────────────────────────────>] 100%

Successfully installed the given mod.
```

**Comment by sharifhsn** [comment]
I got something very similar:
```
✦ ❯ pacmc update
Checking for mod updates for the '.minecraft' archive
Will update the mods at /home/sharif/.minecraft/mods

The mod curseforge/Patchouli (Fabric) is outdated
The mod curseforge/ToroHealth Damage Indicators is up to date
[other mod updates...]
Got a Gateway Time-out answer (code 504) for the following request: https://addons-ecs.forgesvc.net/api/v2/addon/484336/files
Please open an issue with the above error message at https://github.com/jakobkmar/pacmc/issues/new
The following mod could not be checked: curseforge/Netherite Carrots
```

It correctly updated after I tried again, however.

**Comment by jakobkmar** [comment]
Yeah these are errors with this Curseforge API itself, you could use the Modrinth, as its API will probably be more reliable.

In the future, pacmc will also use the new Curseforge API released a few days ago to us, but that will require some more work.
