### ISSUE TITLE
ConcurrentModificationException when changing version of archive

### ISSUE THREAD

**Issue by OneYellowLemon** [jakobkmar/pacmc#29]
I ran `pacmc archive version 1.18.2 fabric118` (`fabric118` being the name of my archive) and got

```java
Trying to change the version of the archive 'fabric118' to '1.18.2'

Changed the version in the database
Redownloading all mods in the archive for the new version...

Retrieving updated file data...
java.util.ConcurrentModificationException
        at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
        at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
        at net.axay.pacmc.commands.Refresh$refreshArchive$2$1$1.invokeSuspend(Refresh.kt:117)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:43)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:106)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
An error occured, Please open an issue with the above stack trace at https://github.com/jakobkmar/pacmc/issues/new
```

OS: Windows 11 Build 21H2

**Comment by jakobkmar** [comment]
Thanks for reporting this, I will have look into it after my exams, but I assume that this will be fixed with the upcoming rewrite.

**Comment by jakobkmar** [comment]
Closing this now with release [0.5.0](https://github.com/jakobkmar/pacmc/releases/tag/0.5.0).
