### ISSUE TITLE
The loader Quilt is not supported by Curseforge

### ISSUE THREAD

**Issue by TwirlySeal** [jakobkmar/pacmc#68]
Installing mods from Curseforge to a Quilt 1.18.2 archive isn't working properly for me. Here's an example with the mod CleanCut.

`pacmc install cleancut` results in the following output:
```
Resolving versions and dependencies...
[+] resolved slugs
java.lang.IllegalStateException: The loader Quilt is not supported by Curseforge
        at net.axay.pacmc.repoapi.curseforge.CurseforgeApi$getProjectVersions$2$1$1.invokeSuspend(CurseforgeApi.kt:68)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

This happens with many other mods on Curseforge as well.

**Comment by btwonion** [comment]
I think it's a curseforge error.

**Comment by jakobkmar** [comment]
Thanks for the report, this is a pacmc "bug" (unimplemented feature), I will fix it once I am back from vacation.
